apiVersion: v2
name: envoy-gateway
description: The Helm chart for Envoy Gateway
type: application

version: 1.4.2
appVersion: "1.4.2"
icon: https://raw.githubusercontent.com/envoyproxy/gateway/main/site/assets/icons/logo.svg

maintainers:
  - name: envoy-gateway-steering-committee
    url: https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
  - name: envoy-gateway-maintainers
    url: https://github.com/envoyproxy/gateway/blob/main/CODEOWNERS

keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg

home: https://gateway.envoyproxy.io/

sources:
  - https://github.com/envoyproxy/gateway
